services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - VCENTER_SYNC_INTERVAL=${VCENTER_SYNC_INTERVAL:-30}
    depends_on:
      - db
    volumes:
      - .:/app
    command: gunicorn --workers ${WEB_CONCURRENCY:-2} --bind 0.0.0.0:5000 run:app

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=vm_inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web

volumes:
  postgres_data:

